<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" ignored="2" total="14" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="542945" started-at="2019-02-15T07:29:12Z" finished-at="2019-02-15T07:38:15Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="542757" started-at="2019-02-15T07:29:12Z" finished-at="2019-02-15T07:38:15Z">
      <class name="com.teyseer.com.teyseer.tests.Masters">
        <test-method status="PASS" signature="Masters(java.lang.String)[pri:1, instance:com.teyseer.com.teyseer.tests.Masters@1c3b9394]" name="Masters" duration-ms="116" started-at="2019-02-15T07:29:12Z" finished-at="2019-02-15T07:29:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[\\DESKTOP-C918GTA\\Keywords\\Master Names Sheet.xlsx]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Masters -->
        <test-method status="FAIL" signature="masterSave()[pri:2, instance:com.teyseer.com.teyseer.tests.Masters@1c3b9394]" name="masterSave" duration-ms="542317" started-at="2019-02-15T07:29:12Z" finished-at="2019-02-15T07:38:15Z">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"css selector","selector":"section[id='mainDiv']"}
  (Session info: chrome=72.0.3626.109)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.10240 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:05:20.749Z'
System info: host: 'FOCUS-QA-29', ip: '192.168.4.51', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.35.528161 (5b82f2d2aae0ca..., userDataDir: C:\Users\sravya\AppData\Loc...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 72.0.3626.109, webStorageEnabled: true}
Session ID: 79060c700b6e930ca8dc6a159e7e967f
*** Element info: {Using=css selector, value=section[id='mainDiv']}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"section[id='mainDiv']"}
  (Session info: chrome=72.0.3626.109)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.10240 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:05:20.749Z'
System info: host: 'FOCUS-QA-29', ip: '192.168.4.51', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.35.528161 (5b82f2d2aae0ca..., userDataDir: C:\Users\sravya\AppData\Loc...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 72.0.3626.109, webStorageEnabled: true}
Session ID: 79060c700b6e930ca8dc6a159e7e967f
*** Element info: {Using=css selector, value=section[id='mainDiv']}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:416)
at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
at com.focus.constants.Menus.menuSelection(Menus.java:136)
at com.teyseer.com.teyseer.tests.Masters.masterSave(Masters.java:152)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterSave -->
      </class> <!-- com.teyseer.com.teyseer.tests.Masters -->
      <class name="com.teyseer.com.teyseer.tests.Transactions">
        <test-method status="FAIL" signature="voucherSaveTest()[pri:3, instance:com.teyseer.com.teyseer.tests.Transactions@6f2cfcc2]" name="voucherSaveTest" duration-ms="285" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[\\DESKTOP-C918GTA\Keywords\Automation Test Cases\OpeningStocks.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: \\DESKTOP-C918GTA\Keywords\Automation Test Cases\OpeningStocks.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.teyseer.com.teyseer.tests.Transactions.voucherSaveTest(Transactions.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- voucherSaveTest -->
      </class> <!-- com.teyseer.com.teyseer.tests.Transactions -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="32" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
      <class name="com.teyseer.com.teyseer.tests.Masters">
        <test-method status="FAIL" signature="Masters(java.lang.String)[pri:1, instance:com.teyseer.com.teyseer.tests.Masters@e84a8e1]" name="Masters" duration-ms="16" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[\\DESKTOP-C918GTA\\Keywords\\Master Others Sheet.xlsx]]>
              </value>
            </param>
          </params>
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[\\DESKTOP-C918GTA\Keywords\Master Others Sheet.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: \\DESKTOP-C918GTA\Keywords\Master Others Sheet.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.teyseer.com.teyseer.tests.Masters.Masters(Masters.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Masters -->
        <test-method status="PASS" signature="masterSave()[pri:2, instance:com.teyseer.com.teyseer.tests.Masters@e84a8e1]" name="masterSave" duration-ms="16" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterSave -->
      </class> <!-- com.teyseer.com.teyseer.tests.Masters -->
    </test> <!-- Test2 -->
    <test name="Test3" duration-ms="31" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
      <class name="com.teyseer.com.teyseer.tests.PriceBook">
        <test-method status="FAIL" signature="priceBookNames(java.lang.String)[pri:1, instance:com.teyseer.com.teyseer.tests.PriceBook@5ddea849]" name="priceBookNames" duration-ms="15" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[\\DESKTOP-C918GTA\\Keywords\\Price Book Names.xlsx]]>
              </value>
            </param>
          </params>
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[\\DESKTOP-C918GTA\Keywords\Price Book Names.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: \\DESKTOP-C918GTA\Keywords\Price Book Names.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.teyseer.com.teyseer.tests.PriceBook.priceBookNames(PriceBook.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- priceBookNames -->
        <test-method status="PASS" signature="priceBook()[pri:2, instance:com.teyseer.com.teyseer.tests.PriceBook@5ddea849]" name="priceBook" duration-ms="16" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- priceBook -->
      </class> <!-- com.teyseer.com.teyseer.tests.PriceBook -->
    </test> <!-- Test3 -->
    <test name="Test4" duration-ms="15" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
      <class name="com.teyseer.com.teyseer.tests.UnitConversion">
        <test-method status="FAIL" signature="UnitConversionNames(java.lang.String)[pri:1, instance:com.teyseer.com.teyseer.tests.UnitConversion@349c1daf]" name="UnitConversionNames" duration-ms="15" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[\\DESKTOP-C918GTA\\Keywords\\UnitConv Names Sheet.xlsx]]>
              </value>
            </param>
          </params>
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[\\DESKTOP-C918GTA\Keywords\UnitConv Names Sheet.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: \\DESKTOP-C918GTA\Keywords\UnitConv Names Sheet.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.teyseer.com.teyseer.tests.UnitConversion.UnitConversionNames(UnitConversion.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UnitConversionNames -->
        <test-method status="PASS" signature="unitConversion()[pri:2, instance:com.teyseer.com.teyseer.tests.UnitConversion@349c1daf]" name="unitConversion" duration-ms="0" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unitConversion -->
      </class> <!-- com.teyseer.com.teyseer.tests.UnitConversion -->
    </test> <!-- Test4 -->
    <test name="Test5" duration-ms="47" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
      <class name="com.teyseer.com.teyseer.tests.TestResults">
        <test-method status="FAIL" signature="testResults()[pri:3, instance:com.teyseer.com.teyseer.tests.TestResults@3a1dd365]" name="testResults" duration-ms="16" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[\\DESKTOP-C918GTA\Keywords\Automation Test Cases\Test Results.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: \\DESKTOP-C918GTA\Keywords\Automation Test Cases\Test Results.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.teyseer.com.teyseer.tests.TestResults.testResults(TestResults.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResults -->
      </class> <!-- com.teyseer.com.teyseer.tests.TestResults -->
      <class name="com.teyseer.com.teyseer.tests.ExchangeRate">
        <test-method status="PASS" signature="LaunchApp()[pri:0, instance:com.teyseer.com.teyseer.tests.ExchangeRate@6b7906b3]" name="LaunchApp" is-config="true" duration-ms="3738" started-at="2019-02-15T07:29:08Z" finished-at="2019-02-15T07:29:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApp -->
        <test-method status="FAIL" signature="exchRateNames(java.lang.String)[pri:1, instance:com.teyseer.com.teyseer.tests.ExchangeRate@6b7906b3]" name="exchRateNames" duration-ms="16" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[\\DESKTOP-C918GTA\\Keywords\\ExchRate Names Sheet.xlsx]]>
              </value>
            </param>
          </params>
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[\\DESKTOP-C918GTA\Keywords\ExchRate Names Sheet.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: \\DESKTOP-C918GTA\Keywords\ExchRate Names Sheet.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.teyseer.com.teyseer.tests.ExchangeRate.exchRateNames(ExchangeRate.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exchRateNames -->
        <test-method status="PASS" signature="exchRate()[pri:2, instance:com.teyseer.com.teyseer.tests.ExchangeRate@6b7906b3]" name="exchRate" duration-ms="0" started-at="2019-02-15T07:38:15Z" finished-at="2019-02-15T07:38:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exchRate -->
      </class> <!-- com.teyseer.com.teyseer.tests.ExchangeRate -->
    </test> <!-- Test5 -->
  </suite> <!-- Default suite -->
</testng-results>
